# Generated by Django 4.2.7 on 2026-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_fakelistingreport_dealercommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarddealerassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
